### ISSUE TITLE
press examples -- reprex vs console and autoplot failure

### ISSUE THREAD

**Issue by jonocarroll** [r-lib/bench#20] opened 2018-05-18 00:35 UTC
I'm having issues running the `README` and help examples for `press`. The fact that this escapes the testing machinery is particularly poignant to me.

If I run the `press` example in a console, it produces `results` with 16 columns

```r
#>  A tibble: 12 x 16
#>    expression   rows  cols      min     mean   median      max `itr/sec` mem_alloc  n_gc n_itr total_time
#>  * <chr>       <dbl> <dbl> <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl> <bch:byt> <dbl> <int>   <bch:tm>
#>  1 bracket     10000    10 918.65µs   1.05ms 987.34µs   1.39ms     950.     1.17MB     2   466   490.27ms
#>  2 which       10000    10 524.29µs 587.91µs 561.42µs   1.02ms    1701.   827.04KB     3   829   487.38ms
#>  3 subset      10000    10 957.46µs   1.05ms   1.03ms   1.49ms     952.     1.28MB     3   456   479.06ms
#>  4 bracket    100000    10  11.68ms  12.82ms  12.93ms  14.73ms      78.0   11.54MB     6    94      1.21s
#>  5 which      100000    10   7.51ms   8.52ms   8.42ms  10.69ms     117.     7.91MB     5    95   809.45ms
#>  6 subset     100000    10  11.69ms  12.75ms  12.75ms  14.63ms      78.4   12.68MB     9    91      1.16s
#>  7 bracket     10000   100   6.03ms   6.55ms    6.4ms   7.41ms     153.     9.71MB     6    94   615.87ms
#>  8 which       10000   100   2.77ms   3.17ms   3.19ms   3.54ms     316.     5.91MB     8   143    453.1ms
#>  9 subset      10000   100   6.17ms   6.97ms   6.92ms   8.93ms     143.     9.84MB     6    94   655.58ms
#> 10 bracket    100000   100  60.79ms  68.04ms  67.83ms  81.22ms      14.7   97.47MB    70    30      2.04s
#> 11 which      100000   100  25.66ms  28.59ms  28.29ms  34.71ms      35.0   59.51MB    43    57      1.63s
#> 12 subset     100000   100  61.78ms  73.47ms  72.73ms  86.09ms      13.6   98.62MB    59    42      3.09s
#>  ... with 4 more variables: result <list>, memory <list>, time <list>, gc <list>
```

but `autoplot` complains that 

```r
ggplot2::autoplot(results)
#> Error: Each column must either be a list of vectors or a list of data frames [time]
```

`traceback()`:

```r
10: stop(cnd)
9: abort(glue("Each column must either be a list of vectors or a list of ", 
       "data frames [{probs}]"))
8: unnest.data.frame(object)
7: NextMethod(.Generic)
6: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
5: suppressWarnings(NextMethod(.Generic))
4: unnest.bench_mark(object)
3: tidyr::unnest(object)
2: autoplot.bench_mark(results)
1: ggplot2::autoplot(results)
```

When I try to produce a `reprex`, `results` contains 12 columns, and `autoplot` still fails

``` r
set.seed(42)

create_df <- function(rows, cols) {
  as.data.frame(setNames(
    replicate(cols, runif(rows, 1, 1000), simplify = FALSE),
    rep_len(c("x", letters), cols)))
}

results <- bench::press(
  rows = c(10000, 100000),
  cols = c(10, 100),
  {
    dat <- create_df(rows, cols)
    bench::mark(
      min_iterations = 100,
      bracket = dat[dat$x > 500, ],
      which = dat[which(dat$x > 500), ],
      subset = subset(dat, x > 500)
    )
  }
)
results
#> # A tibble: 12 x 12
#>    expression   rows  cols      min     mean   median      max `itr/sec`
#>    <chr>       <dbl> <dbl> <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>
#>  1 bracket     10000    10 905.66µs 988.47µs 957.24µs   1.45ms    1012. 
#>  2 which       10000    10 527.89µs 593.52µs 561.57µs 972.45µs    1685. 
#>  3 subset      10000    10   1.05ms   1.15ms   1.12ms   1.57ms     868. 
#>  4 bracket    100000    10  12.86ms  14.13ms  13.59ms  19.01ms      70.8
#>  5 which      100000    10   8.65ms  10.04ms   9.98ms  13.24ms      99.6
#>  6 subset     100000    10  13.73ms  15.06ms   14.4ms  17.86ms      66.4
#>  7 bracket     10000   100   7.04ms   7.91ms   7.93ms   9.09ms     126. 
#>  8 which       10000   100   3.21ms   3.76ms   3.75ms   4.74ms     266. 
#>  9 subset      10000   100   7.25ms   8.15ms   8.02ms  10.64ms     123. 
#> 10 bracket    100000   100  63.99ms  70.29ms  70.27ms  86.13ms      14.2
#> 11 which      100000   100  26.56ms  29.75ms  29.27ms  34.95ms      33.6
#> 12 subset     100000   100  71.63ms  74.91ms  72.88ms  96.92ms      13.3
#> # ... with 4 more variables: mem_alloc <bch:byt>, n_gc <dbl>, n_itr <int>,
#> #   total_time <bch:tm>
ggplot2::autoplot(results)
#> Error: Each column must either be a list of vectors or a list of data frames [time]
```

Created on 2018-05-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_AU:en                    
#>  collate  en_AU.UTF-8                 
#>  tz       Australia/Adelaide          
#>  date     2018-05-18
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                            
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.3)                    
#>  backports    1.1.2      2017-12-13 CRAN (R 3.4.3)                    
#>  base       * 3.4.4      2018-04-21 local                             
#>  bench        0.0.0.9000 2018-05-18 Github (r-lib/bench@b9377d0)      
#>  bindr        0.1.1      2018-03-13 cran (@0.1.1)                     
#>  bindrcpp     0.2.2      2018-03-29 CRAN (R 3.4.3)                    
#>  cli          1.0.0      2017-11-05 CRAN (R 3.4.3)                    
#>  colorspace   1.3-2      2016-12-14 CRAN (R 3.4.3)                    
#>  compiler     3.4.4      2018-04-21 local                             
#>  crayon       1.3.4      2017-09-16 CRAN (R 3.4.3)                    
#>  datasets   * 3.4.4      2018-04-21 local                             
#>  devtools     1.13.5     2018-02-18 CRAN (R 3.4.4)                    
#>  digest       0.6.15     2018-01-28 cran (@0.6.15)                    
#>  dplyr        0.7.4      2017-09-28 CRAN (R 3.4.3)                    
#>  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.3)                    
#>  ggplot2      2.2.1.9000 2018-05-18 Github (tidyverse/ggplot2@4b609fb)
#>  glue         1.2.0      2017-10-29 CRAN (R 3.4.3)                    
#>  graphics   * 3.4.4      2018-04-21 local                             
#>  grDevices  * 3.4.4      2018-04-21 local                             
#>  grid         3.4.4      2018-04-21 local                             
#>  gtable       0.2.0      2016-02-26 CRAN (R 3.4.3)                    
#>  htmltools    0.3.6      2017-04-28 cran (@0.3.6)                     
#>  knitr        1.20       2018-02-20 cran (@1.20)                      
#>  lazyeval     0.2.1      2017-10-29 CRAN (R 3.4.3)                    
#>  magrittr     1.5        2014-11-22 CRAN (R 3.4.3)                    
#>  memoise      1.1.0      2017-04-21 CRAN (R 3.4.3)                    
#>  methods    * 3.4.4      2018-04-21 local                             
#>  munsell      0.4.3      2016-02-13 CRAN (R 3.4.3)                    
#>  pillar       1.2.2      2018-04-26 cran (@1.2.2)                     
#>  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.3)                    
#>  plyr         1.8.4      2016-06-08 CRAN (R 3.4.3)                    
#>  profmem      0.5.0      2018-01-30 cran (@0.5.0)                     
#>  purrr        0.2.4      2017-10-18 CRAN (R 3.4.3)                    
#>  R6           2.2.2      2017-06-17 CRAN (R 3.4.3)                    
#>  Rcpp         0.12.16    2018-03-13 cran (@0.12.16)                   
#>  rlang        0.2.0.9001 2018-05-18 Github (tidyverse/rlang@854174a)  
#>  rmarkdown    1.9.8      2018-04-21 Github (rstudio/rmarkdown@81dabbc)
#>  rprojroot    1.3-2      2018-01-03 cran (@1.3-2)                     
#>  scales       0.5.0.9000 2018-03-05 Github (hadley/scales@d767915)    
#>  stats      * 3.4.4      2018-04-21 local                             
#>  stringi      1.2.2      2018-05-02 CRAN (R 3.4.4)                    
#>  stringr      1.3.0.9000 2018-03-04 Github (tidyverse/stringr@097c0c0)
#>  tibble       1.4.2      2018-01-22 cran (@1.4.2)                     
#>  tidyr        0.8.0      2018-01-29 CRAN (R 3.4.3)                    
#>  tidyselect   0.2.4      2018-02-26 cran (@0.2.4)                     
#>  tools        3.4.4      2018-04-21 local                             
#>  utf8         1.1.3      2018-01-03 cran (@1.1.3)                     
#>  utils      * 3.4.4      2018-04-21 local                             
#>  withr        2.1.2      2018-04-20 Github (r-lib/withr@79d7b0d)      
#>  yaml         2.1.18     2018-03-08 cran (@2.1.18)
```

</details>
<br />

I get the same issue from the example in `?press`.

_Is this expected behaviour (different columns in console vs `reprex`) and is the `autoplot` functionality currently broken?_

**Comment by jimhester** [comment] 2018-05-18 11:39
You need the devel version of tidyr, this should have been installed for you if you used devtools to install the package dependencies.

**Comment by jimhester** [comment] 2018-05-18 11:40
Fixed by 572a7fe

**Comment by jimhester** [comment] 2018-05-18 11:41
Also it doesn't "escape the testing machinery" the testing machinery has devel tidyr installed.

**Closed by jimhester** 2018-05-18 11:40 UTC

**Comment by jimhester** [comment] 2018-05-18 11:42
This is also a duplicate of https://github.com/r-lib/bench/issues/13
