### ISSUE TITLE
Can't take the str() of bench$time

### ISSUE THREAD

**Issue by lionel-** [r-lib/bench#35] opened 2018-09-19 11:13 UTC
```
bench <- bench::mark("foo", "foo")

str(bench$time)
#> List of 2
#>  $ :Error in format.default(res, scientific = scientific, digits = digits,  : 
#>   formal argument "drop0trailing" matched by multiple actual arguments
```

**Comment by jimhester** [comment] 2018-09-19 12:29
This is a duplicate of #32, #22; it is fixed in the devel version of bench.

``` r
bench <- bench::mark("foo", "foo")
str(bench$time)
#> List of 2
#>  $ : 'bench_time' num [1:10000] 0 0 1ns 1ns 0 0 0 0 0 0 ...
#>  $ : 'bench_time' num [1:10000] 12ns 12ns 13ns 0 12ns ...
sessioninfo::package_info("bench")
#>  package    * version date       source                      
#>  assertthat   0.2.0   2017-04-11 CRAN (R 3.5.0)              
#>  bench        1.0.1   2018-09-19 Github (r-lib/bench@eadc1ed)
#>  cli          1.0.0   2017-11-05 CRAN (R 3.5.0)              
#>  crayon       1.3.4   2017-09-16 CRAN (R 3.5.0)              
#>  fansi        0.3.0   2018-08-13 CRAN (R 3.5.0)              
#>  glue         1.3.0   2018-07-17 CRAN (R 3.5.0)              
#>  pillar       1.3.0   2018-07-14 CRAN (R 3.5.0)              
#>  profmem      0.5.0   2018-01-30 CRAN (R 3.5.0)              
#>  rlang        0.2.2   2018-08-16 CRAN (R 3.5.0)              
#>  tibble       1.4.2   2018-01-22 CRAN (R 3.5.0)              
#>  utf8         1.1.4   2018-05-24 CRAN (R 3.5.0)
```

Created on 2018-09-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Closed by jimhester** 2018-09-19 12:29 UTC
