### ISSUE TITLE
bench::mark() freezes with qs::qread() on 356.4MB file

### ISSUE THREAD

**Issue by moldach** [r-lib/bench#66] opened 2019-10-29 19:25 UTC
I'm trying to include some large ggplot2 objects in a Shiny application and some folks suggested that I try out the qs package instead of read/write with base R's `.rds`.

When I tried benchmarking `bench::mark()` function causes RStudio to crash - I tried this on the weekend on my 8Gb laptop and then my 32Gb workstation at work today. Wasn't sure if this is a bug that should be reported to your package, their package (or both) so I cross-posted.

Here's the code I ran:

```
library(bench)
library(qs)
library(sf)
library(cowplot)

# load ggplot
download.file("https://www.dropbox.com/s/ao0827vayr5u3vx/hawaii_agriculture_100m_basemap.rds?raw=1" , "hawaii_agriculture_100m_basemap.rds")
hawaii <- readRDS("hawaii_agriculture_100m_basemap.rds")

# bench mark saving
save_compressed <- bench::mark(saveRDS(hawaii, "hawaii_compressed.rds"), iterations = 50)
save_uncompressed <- bench::mark(saveRDS(hawaii, "hawaii_uncompressed.rds", compress = FALSE), iterations = 50)
save_qs <- bench::mark(qsave(hawaii, "hawaii.qs"), iterations = 50)

# bench mark reading
read_compressed <- bench::mark(hawaii <- readRDS("hawaii_compressed.rds"), iterations = 50)
read_uncompressed <- bench::mark(hawaii <- readRDS("hawaii_uncompressed.rds"), iterations = 50)
read_qs <- bench::mark(hawaii <- qread("hawaii.qs"), iterations = 50)  # This causes workstation to freeze
```

Here's my `sessionInfo()`:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /home/tsundoku/anaconda3/lib/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cowplot_1.0.0  ggplot2_3.2.1  showtext_0.7   showtextdb_2.0 sysfonts_0.8   sf_0.8-0       qs_0.19.1      bench_1.0.4   

loaded via a namespace (and not attached):
  [1] nlme_3.1-141        tsne_0.1-3          bitops_1.0-6        RcppAnnoy_0.0.13    RColorBrewer_1.1-2  httr_1.4.1         
  [7] sctransform_0.2.0   tools_3.6.1         backports_1.1.5     R6_2.4.0            irlba_2.3.3         KernSmooth_2.23-16 
 [13] DBI_1.0.0           uwot_0.1.4          lazyeval_0.2.2      colorspace_1.4-1    withr_2.1.2         npsurv_0.4-0       
 [19] tidyselect_0.2.5    gridExtra_2.3       compiler_3.6.1      plotly_4.9.0        labeling_0.3        Seurat_3.1.1       
 [25] caTools_1.17.1.2    scales_1.0.0        classInt_0.4-2      lmtest_0.9-37       ggridges_0.5.1      pbapply_1.4-2      
 [31] stringr_1.4.0       digest_0.6.22       R.utils_2.9.0       pkgconfig_2.0.3     htmltools_0.4.0     bibtex_0.4.2       
 [37] htmlwidgets_1.5.1   rlang_0.4.1         rstudioapi_0.10     RApiSerialize_0.1.0 zoo_1.8-6           jsonlite_1.6       
 [43] ica_1.0-2           gtools_3.8.1        dplyr_0.8.3         R.oo_1.22.0         magrittr_1.5        Matrix_1.2-17      
 [49] Rcpp_1.0.2          munsell_0.5.0       ape_5.3             reticulate_1.13     lifecycle_0.1.0     R.methodsS3_1.7.1  
 [55] stringi_1.4.3       gbRd_0.4-11         MASS_7.3-51.4       gplots_3.0.1.1      Rtsne_0.15          plyr_1.8.4         
 [61] grid_3.6.1          parallel_3.6.1      gdata_2.18.0        listenv_0.7.0       ggrepel_0.8.1       crayon_1.3.4       
 [67] lattice_0.20-38     splines_3.6.1       SDMTools_1.1-221.1  zeallot_0.1.0       pillar_1.4.2        igraph_1.2.4.1     
 [73] future.apply_1.3.0  reshape2_1.4.3      codetools_0.2-16    leiden_0.3.1        glue_1.3.1          lsei_1.2-0         
 [79] metap_1.1           RcppParallel_4.4.4  data.table_1.12.6   vctrs_0.2.0         png_0.1-7           Rdpack_0.11-0      
 [85] gtable_0.3.0        RANN_2.6.1          purrr_0.3.3         tidyr_1.0.0         future_1.14.0       assertthat_0.2.1   
 [91] rsvd_1.0.2          e1071_1.7-2         class_7.3-15        survival_2.44-1.1   viridisLite_0.3.0   tibble_2.1.3       
 [97] units_0.6-5         cluster_2.1.0       globals_0.12.4      fitdistrplus_1.0-14 ROCR_1.0-7     
```

**Comment by jimhester** [comment] 2020-01-08 16:17
Hi, unfortunately that file 404s for me now. I think it is unlikely that bench is the issue here and in https://github.com/traversc/qs/issues/21 they say they cannot reproduce the crash, so I am closing this.

**Closed by jimhester** 2020-01-08 16:17 UTC
