### ISSUE TITLE
str does not work with bench_bytes class

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/bench#32] opened 2018-09-03 09:37 UTC
`str` does not seem to play well with `bench_bytes`:

```
> p0 <- bench::mark(1:10, seq.int(1, 10))
> p0$mem_alloc
0B 0B
> str(p0$mem_alloc)
Error in format.default(res, scientific = scientific, digits = digits,  : 
  formal argument "drop0trailing" matched by multiple actual arguments
```

**Comment by jimhester** [comment] 2018-09-03 12:47
Duplicate of https://github.com/r-lib/bench/issues/22, this is fixed in the December version of bench

**Closed by jimhester** 2018-09-03 12:47 UTC
